# Generated by Django 5.2.5 on 2025-08-15 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
